sudo: required
language: csharp
solution: d2v.sln
script:
  - xbuild d2v.sln
deploy:   
   edge: true
   provider: cloudfoundry
   username: minakshi.aggarwal@verizon.com
   password: ironfoundry@123
   api: api.beta.ironfoundry.me
   organization: hackersmkv
   space: development